### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by TrySound** [jonschlinkert/inquirer2#1]
(It's much better than async function).then(answers => { console.log('Cool!'); });

**Comment by TrySound** [comment]
Maybe even instead. Do not need to be clone and have any legacy

**Comment by TrySound** [comment]
[bluebird](https://github.com/petkaantonov/bluebird) is the best polyfill [afaik](https://github.com/sindresorhus/ava/issues/232#issuecomment-157266938)

**Comment by jonschlinkert** [comment]
I'm open to it. I've been thinking that promises are a better model for this

**Comment by jonschlinkert** [comment]
> Do not need to be clone and have any legacy

yeah I agree with that too. but the hardest part IMHO is not the flow control, it's the UI stuff. I think we can do better there too.

any ideas for good names? :)

**Comment by TrySound** [comment]
Hm.. don't know. I used only input and confirm before :) I am more insterested in api, but after promise implementation I can think about ui stuff.

**Comment by TrySound** [comment]
@jonschlinkert Can you share me access, please

**Comment by jonschlinkert** [comment]
done!

**Comment by jonschlinkert** [comment]
> Hm.. don't know. I used only input and confirm before :)

I use that the most too. The one I'd really like to split out is choices. it would be nice to have a micro lib for choice questions

**Comment by TrySound** [comment]
@jonschlinkert Maybe something like postcss or babel modules?:)

**Comment by TrySound** [comment]
Or not :) Need to think...

**Comment by jonschlinkert** [comment]
like plugins you mean? if so, yeah that's along the lines of what I was thinking.

**Comment by TrySound** [comment]
@jonschlinkert Do you like es2015? I think in our case (classes, arrows) it will be very helpful.

**Comment by jonschlinkert** [comment]
yes, sure. that would be fine
